In [614]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [615]:
df=pd.read_csv('pick_time_warehouse_train - pick_time_warehouse_train.csv')
df.head(5)

,sl.no,Pick_Time,Start_Time_of_Picking,SKU,Actual_Quantity,User,manning,last_station_served_by_user,number_of_items_container,total_quantity_of_items_in_container,...,Length_of_item,Width_of_item,Cube_of_item,weight_of_each_item,total_time_spent_by_user_in_minutes,total_quantity_picked_by_user,Location,number_of_container_conveyor,station,day
0,896,28.520,21:03.3,23,1,29,2,197,0,0,...,5.25,2.5,0.021,1.0400,137,500.0,166,2,197,27
1,897,0.460,42:45.2,3,6,34,2,143,1,2,...,2.50,2.5,0.031,0.4062,215,855.0,8,1,142,29
2,898,6.013,51:38.0,3,1,64,2,142,1,1,...,2.50,2.5,0.031,0.4062,265,850.0,8,1,142,27
3,899,6.413,54:42.2,13,1,46,2,197,3,3,...,10.00,1.0,0.041,1.1000,397,1121.0,184,0,197,28
4,900,24.263,42:44.6,196,1,38,2,143,4,4,...,7.00,10.0,0.243,3.5000,546,829.0,64,1,143,29

In [616]:
df.isnull().sum()

sl.no                                          0
Pick_Time                                      0
Start_Time_of_Picking                          0
SKU                                            0
Actual_Quantity                                0
User                                           0
manning                                        0
last_station_served_by_user                    0
number_of_items_container                      0
total_quantity_of_items_in_container           0
volume_of_items_present_in_container           0
Total_Weight_of_items_present_in_container     0
volume_of_items                                0
Height_of_item                                 0
Length_of_item                                 0
Width_of_item                                  0
Cube_of_item                                   0
weight_of_each_item                            0
total_time_spent_by_user_in_minutes            0
total_quantity_picked_by_user                 19
Location                                       0
number_of_container_conveyor                   0
station                                        0
day                                            0
dtype: int64

In [617]:
df=df.fillna(method='ffill')
df.head(5)

,sl.no,Pick_Time,Start_Time_of_Picking,SKU,Actual_Quantity,User,manning,last_station_served_by_user,number_of_items_container,total_quantity_of_items_in_container,...,Length_of_item,Width_of_item,Cube_of_item,weight_of_each_item,total_time_spent_by_user_in_minutes,total_quantity_picked_by_user,Location,number_of_container_conveyor,station,day
0,896,28.520,21:03.3,23,1,29,2,197,0,0,...,5.25,2.5,0.021,1.0400,137,500.0,166,2,197,27
1,897,0.460,42:45.2,3,6,34,2,143,1,2,...,2.50,2.5,0.031,0.4062,215,855.0,8,1,142,29
2,898,6.013,51:38.0,3,1,64,2,142,1,1,...,2.50,2.5,0.031,0.4062,265,850.0,8,1,142,27
3,899,6.413,54:42.2,13,1,46,2,197,3,3,...,10.00,1.0,0.041,1.1000,397,1121.0,184,0,197,28
4,900,24.263,42:44.6,196,1,38,2,143,4,4,...,7.00,10.0,0.243,3.5000,546,829.0,64,1,143,29

In [618]:
df.isnull().sum()

sl.no                                         0
Pick_Time                                     0
Start_Time_of_Picking                         0
SKU                                           0
Actual_Quantity                               0
User                                          0
manning                                       0
last_station_served_by_user                   0
number_of_items_container                     0
total_quantity_of_items_in_container          0
volume_of_items_present_in_container          0
Total_Weight_of_items_present_in_container    0
volume_of_items                               0
Height_of_item                                0
Length_of_item                                0
Width_of_item                                 0
Cube_of_item                                  0
weight_of_each_item                           0
total_time_spent_by_user_in_minutes           0
total_quantity_picked_by_user                 0
Location                                      0
number_of_container_conveyor                  0
station                                       0
day                                           0
dtype: int64

In [619]:
li=[]
r=[]
for i in range(df.shape[0]):
    li.append(df['Start_Time_of_Picking'].iloc[i].split(':'))
for i in range(df.shape[0]):
    r.append((float(li[i][0])*60)+float(li[i][1]))
df2=pd.DataFrame(data=r)
df2
df['Start_Time_of_Picking']=df2
df['Start_Time_of_Picking']

0        1263.3
1        2565.2
2        3098.0
3        3282.2
4        2564.6
          ...
46299    2390.5
46300    1857.7
46301    2148.2
46302    2406.3
46303    3267.7
Name: Start_Time_of_Picking, Length: 46304, dtype: float64

In [620]:
# df['Start_Time_of_Picking']=pd.to_datetime(df.Start_Time_of_Picking)
# df.head(5)

In [621]:
x=df
x=x.drop(columns=['sl.no','Pick_Time','last_station_served_by_user'])
x.head(5)

,Start_Time_of_Picking,SKU,Actual_Quantity,User,manning,number_of_items_container,total_quantity_of_items_in_container,volume_of_items_present_in_container,Total_Weight_of_items_present_in_container,volume_of_items,...,Length_of_item,Width_of_item,Cube_of_item,weight_of_each_item,total_time_spent_by_user_in_minutes,total_quantity_picked_by_user,Location,number_of_container_conveyor,station,day
0,1263.3,23,1,29,2,0,0,0.000000,0.0000,36.09375,...,5.25,2.5,0.021,1.0400,137,500.0,166,2,197,27
1,2565.2,3,6,34,2,1,2,260.156250,4.4600,318.75000,...,2.50,2.5,0.031,0.4062,215,855.0,8,1,142,29
2,3098.0,3,1,64,2,1,1,204.750000,0.6875,53.12500,...,2.50,2.5,0.031,0.4062,265,850.0,8,1,142,27
3,3282.2,13,1,46,2,3,3,586.125000,3.7500,70.00000,...,10.00,1.0,0.041,1.1000,397,1121.0,184,0,197,28
4,2564.6,196,1,38,2,4,4,995.859375,2.5250,420.00000,...,7.00,10.0,0.243,3.5000,546,829.0,64,1,143,29

In [622]:
y=df.iloc[:,1]
y.head(5)

0    28.520
1     0.460
2     6.013
3     6.413
4    24.263
Name: Pick_Time, dtype: float64

In [623]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
x_train.head(5)

,Start_Time_of_Picking,SKU,Actual_Quantity,User,manning,number_of_items_container,total_quantity_of_items_in_container,volume_of_items_present_in_container,Total_Weight_of_items_present_in_container,volume_of_items,...,Length_of_item,Width_of_item,Cube_of_item,weight_of_each_item,total_time_spent_by_user_in_minutes,total_quantity_picked_by_user,Location,number_of_container_conveyor,station,day
4453,1474.3,70,2,16,1,9,14,794.250000,7.7538,52.812500,...,3.25,3.25,0.015,0.3312,57,156.0,144,1,197,28
21211,1768.4,42,1,37,2,10,10,851.319375,9.5375,146.625000,...,11.50,4.25,0.085,1.8400,58,189.0,200,2,179,23
46136,422.3,261,1,84,1,3,3,106.000000,2.4400,15.125016,...,2.92,2.91,0.009,0.3400,338,466.0,223,2,179,26
6150,21.3,12,1,20,2,1,1,119.531250,1.1600,34.000000,...,8.50,2.00,0.020,1.0400,398,937.0,34,0,142,21
1242,946.3,196,1,73,2,3,4,319.062500,1.5209,420.000000,...,7.00,10.00,0.243,3.5000,192,720.0,64,0,143,27

In [624]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [625]:
y_pred=regressor.predict(x_test)
y_pred

array([17.99297786, 16.80620514, 13.89151945, ..., 19.5069751 ,
       15.49318813, 14.58982557])

In [626]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.06199504500657582

In [627]:
from sklearn.decomposition import PCA
pca=PCA(n_components=18)
x_train=pca.fit_transform(x_train)
x_test=pca.transform(x_test)

In [628]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [629]:
y_pred=regressor.predict(x_test)
y_pred

array([17.85042415, 17.59476395, 14.85158794, ..., 19.74758407,
       15.54616379, 13.86242735])

In [630]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.061359901144726225